name       : minikube
version    : 0.24.1
release    : 2
source     :
    - git|https://github.com/kubernetes/minikube.git : v0.24.1
license    : Apache-2.0
component  : system.tools
summary    : Kubernetes development environment
networking : yes
extract    : no
description: |
    Minikube makes it easy to create all in one VirtualBox VMs with kubernetes for local development.
builddeps  :
    - git
    - golang
setup      : |
    export GOPATH=$workdir
    mkdir {pkg,src}
    mkdir -p src/k8s.io/minikube
    cd src/k8s.io/minikube/
    cp -R $sources/minikube.git/* .
    cp -R $sources/minikube.git/.git .
    cp -R vendor/* $workdir/src/
build      : |
    export GOPATH=$workdir
    export PATH=$PATH:$GOPATH/bin
    cd $workdir/src/k8s.io/minikube
    %make
check      : |
    export GOPATH=$workdir
    export PATH=$PATH:$GOPATH/bin
    cd $workdir/src/k8s.io/minikube
    %make test
install    : |
    install -D -d -m 00755 $installdir/usr/bin
    install -D -m 00755 $workdir/src/k8s.io/minikube/out/minikube $installdir/usr/bin/minikube
