name       : minikube
version    : 1.30.1
release    : 47
source     :
    - git|https://github.com/kubernetes/minikube.git : v1.30.1
license    : Apache-2.0
component  : system.utils
summary    : Kubernetes development environment
networking : yes
extract    : no
description: |
    Minikube makes it easy to create all in one VirtualBox VMs with kubernetes for local development.
builddeps  :
    - golang
    - libvirt-devel
environment: |
    export GOPATH=$PKG_BUILD_DIR
    export PATH=$PATH:$GOPATH/bin
    export MINIKUBE=$GOPATH/src/k8s.io/minikube
setup      : |
    mkdir -p $MINIKUBE
    cp -R $sources/minikube.git/* $MINIKUBE
build      : |
    cd $MINIKUBE
    %make
check      : |
    cd $MINIKUBE
    # This script needs to be run before `make test` to fix boilerplate for test
    hack/boilerplate/fix.sh
    %make -j2 test
install    : |
    install -D -d -m 00755 $installdir/usr/bin
    install -D -m 00755 $MINIKUBE/out/minikube $installdir/usr/bin/minikube
    # Install completion scripts
    $MINIKUBE/out/minikube completion bash > minikube-bash-completion
    $MINIKUBE/out/minikube completion zsh > minikube-zsh-completion
    install -Dm00644 minikube-bash-completion $installdir/usr/share/bash-completion/completions/minikube
    install -Dm00644 minikube-zsh-completion $installdir/usr/share/zsh/site-functions/_minikube
