name       : minikube
version    : 1.1.1
release    : 11
source     :
    - git|https://github.com/kubernetes/minikube.git : v1.1.1
license    : Apache-2.0
component  : system.tools
summary    : Kubernetes development environment
networking : yes
extract    : no
description: |
    Minikube makes it easy to create all in one VirtualBox VMs with kubernetes for local development.
builddeps  :
    - git
    - golang
    - libvirt-devel
environment: |
    export GOPATH=$workdir
    export PATH=$PATH:$GOPATH/bin
    export MINIKUBE=$workdir/src/k8s.io/minikube
setup      : |
    mkdir -p {pkg,src/k8s.io/}
    cp -R $sources/minikube.git $MINIKUBE
    cd $MINIKUBE
    # patch golangci-lint
    %patch -p1 < $pkgfiles/0001-Update-Makefile-to-use-golangci-lint-v1.17.1.patch
    %patch -p1 < $pkgfiles/0002-Simplify-the-Make-code-use-a-GOLINT_VERSION-var.patch
build      : |
    cd $MINIKUBE
    %make
check      : |
    cd $MINIKUBE
    %make test
install    : |
    install -D -d -m 00755 $installdir/usr/bin
    install -D -m 00755 $MINIKUBE/out/minikube $installdir/usr/bin/minikube
    # Install completion scripts
    $MINIKUBE/out/minikube completion bash > minikube-bash-completion
    $MINIKUBE/out/minikube completion zsh > minikube-zsh-completion
    install -Dm00644 minikube-bash-completion $installdir/usr/share/bash-completion/completions/minikube
    install -Dm00644 minikube-zsh-completion $installdir/usr/share/zsh/site-functions/_minikube
