name       : minikube
version    : 1.6.2
release    : 17
source     :
    - git|https://github.com/kubernetes/minikube.git : v1.6.2
license    : Apache-2.0
component  : system.tools
summary    : Kubernetes development environment
networking : yes
extract    : no
description: |
    Minikube makes it easy to create all in one VirtualBox VMs with kubernetes for local development.
builddeps  :
    - golang
    - libvirt-devel
environment: |
    export GOPATH=$PKG_BUILD_DIR
    export PATH=$PATH:$GOPATH/bin
    export MINIKUBE=$GOPATH/src/k8s.io/minikube
setup      : |
    mkdir -p $MINIKUBE
    cp -R $sources/minikube.git/* $MINIKUBE

    # pre-fetch go-bindata manually (replace dead fork with maintained one)
    cd $MINIKUBE
    GO111MODULE=off GOBIN=$GOPATH/bin go get github.com/shuLhan/go-bindata/...
build      : |
    cd $MINIKUBE
    %make
check      : |
    cd $MINIKUBE
    %make test
install    : |
    install -D -d -m 00755 $installdir/usr/bin
    install -D -m 00755 $MINIKUBE/out/minikube $installdir/usr/bin/minikube
    # Install completion scripts
    $MINIKUBE/out/minikube completion bash > minikube-bash-completion
    $MINIKUBE/out/minikube completion zsh > minikube-zsh-completion
    install -Dm00644 minikube-bash-completion $installdir/usr/share/bash-completion/completions/minikube
    install -Dm00644 minikube-zsh-completion $installdir/usr/share/zsh/site-functions/_minikube
