name       : minikube
version    : 0.16.0
release    : 1
source     :
    - git|https://github.com/kubernetes/minikube.git : v0.16.0
license    : Apache-2.0
component  : system.tools
summary    : Kubernetes development environment
networking : yes
extract    : no
description: |
    Minikube makes it easy to create all in one VirtualBox VMs with kubernetes for local development.
builddeps  :
    - git
    - golang
    - mercurial
setup      : |
    mkdir {pkg,src}
    mkdir -p src/k8s.io/minikube
    cd src/k8s.io/minikube/
    cp -R $sources/minikube.git/* .
    cp -R $sources/minikube.git/.git .
    cp -R vendor/* $workdir/src/
build      : |
    cd $workdir/src/k8s.io/minikube
    %make
install    : |
    cd $workdir/src/k8s.io/minikube
    install -Dm 00755 out/minikube $installdir/usr/bin/minikube
